# This is a basic workflow to help you get started with Actions
name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    name: Build and test fluter_command on stable flutter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:                
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      # Checks-out the respective branch.
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      
      - name: Install dependencies
        run: flutter pub get        
                   
      # Exits the workflow if any format is carried out.
      # from docs:   --set-exit-if-changed    Return exit code 1 if there are any formatting changes.
      - name: Check format
        run: dart format --set-exit-if-changed .
      
      # Carry out an flutter analysis      
      # - name: Analyze
      #   run: flutter analyze
      #   working-directory: ${{ matrix.dirs }}
      # If golden files are added then this should be handled differently for different OS
      - name: Run tests
        run: flutter test --coverage
      
      # Code coverage can be acitivated once its ready.
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
